version: '3'

services:
  client:
    build:
      context: ./client
    ports:
      - "5173:80"
    volumes:
      - ./client:/app

  server:
    build:
      context: ./server
    env_file:
      - ./server/.env.local
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app

networks:
  default:
    driver: bridge
